name: "Security Pipeline (SAST & DAST)"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '36 22 * * 6'

jobs:
  # TAREFA 1: SAST com CodeQL
  sast_scan:
    name: Analyze (CodeQL SAST)
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
        - language: javascript-typescript
          build-mode: none
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
        build-mode: ${{ matrix.build-mode }}
        queries: security-and-quality

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"

  # TAREFA 2: DAST com OWASP ZAP
  dast_scan:
    name: Scan with OWASP ZAP (DAST)
    runs-on: ubuntu-latest
    # Garante que o DAST só rode após o SAST
    needs: sast_scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install

      - name: Run API in background
        run: |
          npx expo start --web &
          sleep 60

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:8081'
          # A ação irá gerar o arquivo 'report_html.html', mas não fará o upload

      - name: Upload ZAP Report
        if: always() # Garante que o relatório seja carregado mesmo que o ZAP encontre vulnerabilidades
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-report # Nome do artefato
          path: report_html.html # Arquivo a ser carregado
